"""Contract tests for optimization MCP tools registration and annotations."""

from __future__ import annotations

from pathlib import Path

import pytest
from fastmcp import Client
from fastmcp.exceptions import ToolError

from google_meridian_mcp_server.server import create_server

# Real, tiny fitted-model fixtures generated by scripts/generate_validation_models.py
# (same fixtures scripts/validation/live_validate.py points the server at). Building
# them here is idempotent — build_variant() skips any that already exist on disk.
_VALIDATION_MODELS_ROOT = Path(__file__).resolve().parents[2] / "models" / "_validation"


@pytest.fixture
async def client(monkeypatch, tmp_path):
    """In-process MCP client wired to the on-disk validation model fixtures.

    Mirrors the local-backend setup in scripts/validation/live_validate.py: point
    the server at models/_validation (building any missing fixtures) so tools that
    resolve a real model_id (e.g. "national-revenue") work end-to-end.
    """
    from scripts.generate_validation_models import build_all

    build_all(_VALIDATION_MODELS_ROOT, force=False)

    monkeypatch.setenv("PERSISTENCE_BACKEND", "local")
    monkeypatch.setenv("LOCAL_MODELS_ROOT", str(_VALIDATION_MODELS_ROOT))
    monkeypatch.setenv("RESULT_CACHE_ENABLED", "false")
    monkeypatch.setenv("OPTIMIZATION_RUNS_ROOT", str(tmp_path / "optimizations"))

    mcp = create_server()
    async with Client(mcp) as connected_client:
        yield connected_client


@pytest.mark.asyncio
async def test_optimization_tools_registered():
    mcp = create_server()
    tools = {t.name for t in await mcp.list_tools()}
    assert {
        "run_optimization",
        "get_optimization_status",
        "get_optimization_result",
        "list_optimizations",
        "delete_optimization",
    } <= tools


@pytest.mark.asyncio
async def test_run_optimization_annotations_not_readonly():
    mcp = create_server()
    by_name = {t.name: t for t in await mcp.list_tools()}
    # run_optimization has no annotations (bare @mcp.tool) — not read-only
    run_opt_annotations = by_name["run_optimization"].annotations
    assert run_opt_annotations is None or run_opt_annotations.readOnlyHint is not True
    assert by_name["get_optimization_status"].annotations.readOnlyHint is True
    assert by_name["get_optimization_result"].annotations.readOnlyHint is True
    assert by_name["list_optimizations"].annotations.readOnlyHint is True
    delete_ann = by_name["delete_optimization"].annotations
    assert delete_ann is None or delete_ann.readOnlyHint is not True


@pytest.mark.asyncio
async def test_cancel_tool_registered_not_readonly():
    mcp = create_server()
    by_name = {t.name: t for t in await mcp.list_tools()}
    assert "cancel_optimization" in by_name
    cancel_ann = by_name["cancel_optimization"].annotations
    assert cancel_ann is None or cancel_ann.readOnlyHint is not True


def _prop(schema: dict, name: str) -> dict:
    return schema["properties"][name]


def _enum_values(prop: dict) -> set[str]:
    # Literal[...] renders either as a top-level "enum" or, for Optional,
    # inside an "anyOf" branch that carries the "enum".
    if "enum" in prop:
        return set(prop["enum"])
    for branch in prop.get("anyOf", []):
        if "enum" in branch:
            return set(branch["enum"])
    return set()


@pytest.mark.asyncio
async def test_compute_tier_and_status_are_enums():
    mcp = create_server()
    by_name = {t.name: t for t in await mcp.list_tools()}

    tier = _prop(by_name["run_optimization"].to_mcp_tool().inputSchema, "compute_tier")
    assert _enum_values(tier) == {"auto", "local", "cloud_cpu", "cloud_gpu"}
    assert tier.get("default") == "auto"

    status = _prop(by_name["list_optimizations"].to_mcp_tool().inputSchema, "status")
    assert _enum_values(status) == {
        "queued",
        "running",
        "completed",
        "failed",
        "canceled",
    }
    # status is optional: omitting it returns all states.
    assert status.get("default") is None
    assert any(branch.get("type") == "null" for branch in status.get("anyOf", []))


@pytest.mark.asyncio
async def test_run_future_optimization_submit_envelope(client):
    res = await client.call_tool(
        "run_future_optimization",
        {
            "model_id": "national-revenue",
            "config": {
                "scenario": {"type": "fixed_budget"},
                "future": {"start_date": "2099-01-01", "horizon": 4},
            },
        },
    )
    data = res.data
    run_id = data.get("run_id")
    try:
        assert data["status"] in ("queued", "running", "completed")
        assert run_id and "compute_tier_resolved" in data
    finally:
        # Reap the submitted run: cancel terminates the worker subprocess spawned
        # by SubprocessExecutor, then delete removes the run record, so no
        # orphaned process or on-disk artifact survives the test.
        if run_id:
            await client.call_tool("cancel_optimization", {"run_id": run_id})
            await client.call_tool("delete_optimization", {"run_id": run_id})


@pytest.mark.asyncio
async def test_run_future_optimization_unknown_channel_errors(client):
    # Reaches the service (real model resolved) -> flat invalid_optimization_config
    # envelope, not a protocol-level error.
    res = await client.call_tool(
        "run_future_optimization",
        {
            "model_id": "national-revenue",
            "config": {
                "scenario": {"type": "fixed_budget"},
                "future": {
                    "start_date": "2099-01-01",
                    "horizon": 4,
                    "cost_multipliers": {"not_a_channel": 1.2},
                },
            },
        },
    )
    assert res.data["error_code"] == "invalid_optimization_config"


@pytest.mark.asyncio
async def test_run_future_optimization_horizon_zero_is_protocol_error(client):
    # horizon=0 violates FutureBlock's pydantic gt=0 at FastMCP input validation,
    # BEFORE the tool body runs -> a protocol-level tool error (ToolError), not
    # the flat {"error_code", ...} envelope.
    with pytest.raises(ToolError):
        await client.call_tool(
            "run_future_optimization",
            {
                "model_id": "national-revenue",
                "config": {
                    "scenario": {"type": "fixed_budget"},
                    "future": {"start_date": "2099-01-01", "horizon": 0},
                },
            },
        )


# Dark-channel fail-fast + excluded-dark tolerance are covered at unit
# (test_optimizer_facade.py) and integration (test_optimizer_facade_future.py)
# layers; the fixture has no naturally-dark channel to exercise here.
@pytest.mark.asyncio
async def test_run_future_optimization_excluded_channels_submits(client):
    res = await client.call_tool(
        "run_future_optimization",
        {
            "model_id": "national-revenue",
            "config": {
                "scenario": {"type": "fixed_budget"},
                "future": {
                    "start_date": "2099-01-01",
                    "horizon": 4,
                    "excluded_channels": ["ch_0"],
                },
            },
        },
    )
    data = res.data
    run_id = data.get("run_id")
    try:
        assert data["status"] in ("queued", "running", "completed")
        assert run_id and "run_id" in data
    finally:
        if run_id:
            await client.call_tool("delete_optimization", {"run_id": run_id})


@pytest.mark.asyncio
async def test_run_future_optimization_exclude_unknown_channel_errors(client):
    res = await client.call_tool(
        "run_future_optimization",
        {
            "model_id": "national-revenue",
            "config": {
                "scenario": {"type": "fixed_budget"},
                "future": {
                    "start_date": "2099-01-01",
                    "horizon": 4,
                    "excluded_channels": ["not_a_channel"],
                },
            },
        },
    )
    assert res.data["error_code"] == "invalid_optimization_config"


@pytest.mark.asyncio
async def test_run_future_optimization_exclude_all_errors(client):
    res = await client.call_tool(
        "run_future_optimization",
        {
            "model_id": "national-revenue",
            "config": {
                "scenario": {"type": "fixed_budget"},
                "future": {
                    "start_date": "2099-01-01",
                    "horizon": 4,
                    "excluded_channels": [
                        "ch_0",
                        "ch_1",
                        "ch_2",
                        "rf_ch_0",
                        "rf_ch_1",
                    ],
                },
            },
        },
    )
    assert res.data["error_code"] == "invalid_optimization_config"
